# Generated by Django 5.1.6 on 2025-03-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(default='mycart', max_length=50),
            preserve_default=False,
        ),
    ]
